image:
  repository: "sonarqube"
  tag: "24.12.0.100206-community"
readinessProbe:
  initialDelaySeconds: 500
livenessProbe:
  initialDelaySeconds: 500
startupProbe:
  initialDelaySeconds: 500

    #service:
  #  type: LoadBalancer

OpenShift:
  enabled: true
  route:
    enabled: true
    path: "/"
    tls:
      insecureEdgeTerminationPolicy: Redirect
    annotations:
      haproxy.router.openshift.io/timeout: 1m

postgresql:
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

elasticsearch:
  bootstrapChecks:  false

plugins:
  install:
    - https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.23.0/sonarqube-community-branch-plugin-1.23.0.jar
sonarProperties:
  sonar.web.javaAdditionalOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.23.0.jar=web"
  sonar.ce.javaAdditionalOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.23.0.jar=ce"

resources:
  limits:
    cpu: 600m
    memory: 4096M
    ephemeral-storage: 50Gi
  requests:
    cpu: 300m
    memory: 2048M
    ephemeral-storage: 10Gi