name: Deploy SonarQube to AKS

on:
  workflow_dispatch:

jobs:
  deploy-sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install kubelogin
        run: |
          sudo az aks install-cli

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Add SonarQube Helm repository
        run: |
          helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
          helm repo update

      - name: Create namespaceS
        run: |
          kubectl create namespace sonarqube

      - name: Deploy SonarQube
        run: |
          helm upgrade --install -n sonarqube sonarqube sonarqube/sonarqube -f charts/sonarqube/sonarqubeValues.yaml --debug
